Lesson 8 active storage
DADUSHKA/third_part_course pull request #6
Opened 2019-04-13 06:22 UTC by DADUSHKA

2019-04-13 06:29 UTC, DADUSHKA commented
спеки контроллера выдают: 
4) AnswersController DELETE #delete_attach_file attach file question re-renders new view
     Failure/Error: @file =  ActiveStorage::Attachment.find(params[:id])
     
     ActiveRecord::RecordNotFound:
       Couldn't find ActiveStorage::Attachment with 'id'=#<Rack::Test::UploadedFile:0x00007f5ffc5e9b70>
не могу понять что им нужно

2019-04-13 06:35 UTC, DADUSHKA commented
А с 'Реализовать хранение файлов через Amazon S3' c моей крымской картой Мир не смог ни где зарегистрироваться, даже Яндекс "ругается".

2019-04-13 10:00 UTC, vkurennov requested changes

2019-04-13 10:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def delete_attach_file
дублирование. здесь и в контрорллере вопросов, при том, что код одинаковый практически. Лучше сделать отдельный контроллер с методом  destroy

2019-04-13 10:00 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def delete_attach_file
а вот и дублирование

2019-04-13 10:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    let(:delete_action) { delete :delete_attach_file, params: { id: file }, format: :js }
Понимаешь id аттачмента (число) != самому файлу. Здесь ты пытаешься передавать вместо id сам файл, из-за этого и ошибка. И если внимательно ее прочитать, то там ровно об это и написано, что рельсы не знают  как файл преобразовать в id.

2019-04-14 11:30 UTC, vkurennov requested changes

2019-04-14 11:30 UTC, vkurennov commented on app/controllers/attach_file_controller.rb
> +  def destroy
а где проверка на автора? Получается, кто угодно может удалить какой-угодно аттачмент.

2019-04-14 11:30 UTC, vkurennov commented on spec/controllers/attach_file_controller_spec.rb
> +      it "for the answer" do
У тебя один контроллер, он вообще никак не зависит от типа родительского объекта, поэтому не нужно проверять на всех возможных типах, потому что их может быть сколь угодно много. А вот что нужно сделать - так это проверить поведение системы для автора и для не автора родительского объекта

2019-04-15 08:34 UTC, vkurennov approved these changes

2019-04-15 18:52 UTC, merged