Lesson 10 rails ujs
DADUSHKA/third_part_course pull request #8
Opened 2019-04-25 06:31 UTC by DADUSHKA

2019-04-25 08:18 UTC, vkurennov requested changes

2019-04-25 08:18 UTC, vkurennov commented on app/assets/javascripts/questions.js
> + $('.question').on('ajax:success', function(e) {
обработчики для вопросов и ответов практически одинаковые, тем более, что класс объекта приходит в json, значит, можно сделать один, универсальный обработчик

2019-04-25 08:18 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +    votes.find_by(user_id: user.id).delete unless user_voted?(user)
тут какая-то неясная логика. мы удаляем голос за этот объект, если пользователь за него же не голосовал. но как тогда может быть голос за этот объект от юзера, если пользователь НЕ голосовал за него??

2019-04-25 08:18 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +  def user_voted?(user)
а зачем вводить этот метод, если у тебя везде есть user и можно к его методу `voted?` и обращаться?

2019-04-25 08:18 UTC, vkurennov commented on app/models/vote.rb
> +  validates :choice, inclusion: (-1..1)
тут массив должен быть `[-1, 1]`, т.к. только 2 значения допустимы, в твоем случае, тут еще и ноль допустим.

2019-04-25 08:18 UTC, vkurennov commented on app/views/answers/_answer.html.slim
>        /вывод ссылки для ответа
эти комментарии точно несут пользу? все же из кода понятно, а код должен быть самодокументируемым и понятным без комментариев

2019-04-25 08:18 UTC, vkurennov commented on spec/models/answer_spec.rb
>    it { should belong_to(:question) }
почему тут нет для votable тестов?

2019-04-25 08:18 UTC, vkurennov commented on spec/models/user_spec.rb
>    it { should have_many(:questions).dependent(:destroy) }
где тесты на  `voted?`

2019-04-25 08:18 UTC, vkurennov commented on spec/support/concerns/voteable_spec.rb
> +    it { expect(Vote.last.choice).to eq 1 }
нужн проверить ассоциации созданного голоса: то, что он связался с юзером и с объектом, за который был голос.

2019-04-25 08:18 UTC, vkurennov commented on spec/support/concerns/voteable_spec.rb
> +    it { expect(Vote.last).to eq nil }
лучше проверять, что кол-во голосов не изменилось, да и блок before для одного теста смысла не имеет

2019-04-25 08:18 UTC, vkurennov commented on spec/support/concerns/voteable_spec.rb
> +    it { expect(Vote.last.choice).to eq 1 }
это не гарантирует того, что сумма голосов не 2. Ты же создал 2 голоса, оба "за", понятно, что последний будет со значением 1 (у тебя в принципе голоса могут иметь знаение только 1/-1). Т.е. здесь нет проверки на то, что не было создано 2 голоса

2019-04-25 08:18 UTC, vkurennov commented on spec/support/concerns/voteable_spec.rb
> +    it { expect(Vote.last.choice).to eq -1 }
тут тоже надо проверять ассоциации, одного значения мало

2019-04-25 08:18 UTC, vkurennov commented on spec/support/concerns/voteable_spec.rb
> +    it { expect(Vote.last).to eq nil }
используй проверку на change

2019-04-25 08:18 UTC, vkurennov commented on spec/support/concerns/voteable_spec.rb
> +  describe 'repeat voting dislike' do
те же замечания, что и для like

2019-04-25 08:18 UTC, vkurennov commented on spec/support/concerns/voteable_spec.rb
> +    it { expect(resource.choice).to eq 5 }
лучше создать несколько голосов "за" и несколько "против" и проверить сумму.

2019-04-26 15:57 UTC, DADUSHKA commented on app/views/answers/_answer.html.slim
>        /вывод ссылки для ответа
это больше для себя, так быстрее ориентироваться

2019-04-27 08:35 UTC, vkurennov approved these changes

2019-04-27 08:35 UTC, vkurennov commented on app/models/user.rb
> +  has_many :votes
`dependent: :destroy` здесь имел смысл

2019-04-29 09:31 UTC, merged